- name: Vagrant Rails apps development
  hosts: all
  user: vagrant
  become: yes
  gather_facts: yes

  roles:
    - role: rvm.ruby
      rvm1_rubies: ['ruby-2.5.3']
      rvm1_bundler_install: true
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_install_path: "/home/vagrant/.rvm"
      rvm1_user: 'vagrant'
      sudo: yes
      tags: ruby


  tasks:
    - name: Install essential apps and tools
      apt:
        name: '{{ item }}'
        state: present
        update-cache: yes
      with_items:
        - htop
        - curl
        - vim
        - lsof
        - unzip
        - p7zip-full
        - postgresql-client
        - gnupg
        - software-properties-common
      become: yes


      # Python3
      # =======
    - ame: Python3 - Install pip3 & Virtual env
      apt:
        name: '{{ item }}'
        force: yes
        state: present
      with_items:
        - python3-pip
      become: yes
      tags: python3
      # END - Python Utils ===============


      # Install Postgresql 10
      # =====================
    - name: Postgresql-10 - Install postgresql database and Dependencies
      apt:
        pkg: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
      - postgresql-10
      - postgresql-contrib-10
      - libpq-dev
      tags: postgresql

    - name: Postgresql-10 - Install postgresql pip dependencies
      pip:
        name: psycopg2
        state: present
      tags: postgresql

    - name: Postgresql-10 - Passwordless login for postgres user
      copy:
        src: "pg_hba_local.conf"
        dest: "/etc/postgresql/10/main/pg_hba.conf"
        owner: postgres
        group: postgres
        mode: 0640
      register: pg_hba
      tags: postgresql

    - name: Postgresql-10 - Add database user
      become_user: postgres
      postgresql_user:
        name: postgres
        role_attr_flags: SUPERUSER
      tags: postgresql

    - name: Postgresql-10 - Enable postgresql to be access from host
      replace:
        path: "/etc/postgresql/10/main/postgresql.conf"
        regexp: "^#listen_addresses = 'localhost'"
        replace: "listen_addresses = '*'"
      become: yes
      tags: postgresql

    - name: Postgresql-10 - Enable and start postgresql
      systemd:
        name: postgresql.service
        enabled: yes
        state: started
      tags: postgresql

    - name: Postgresql-10 - Restart service after customization
      service:
        name: postgresql.service
        state: restarted
      tags: postgresql
      # END - Install Postgresql 10 ===============


      # Nodejs 10 & Yarn
      # ================
    - name: Nodejs - Add apt repo
      shell: "{{ item }}"
      with_items:
        - curl -sL https://deb.nodesource.com/setup_10.x | sudo bash
      become: true
      run_once: true
      tags: nodejs

    - name: Nodejs - Install nodejs & yarn
      apt:
        name: "{{ item }}"
        state: present
        update-cache: yes
      become: true
      with_items:
        - nodejs
        - yarn
      tags: nodejs
      # END - Install Nodejs & Yarn

      # Environment variable
    - name: Environment - Setup env variables
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: "^{{ item }}"
        line: "{{ item }}"
      with_items:
        - DATABASE_USERNAME=postgres
        - DATABASE_PASSWORD=
        - DATABASE_HOST=localhost
        - DATABASE_PORT=5432
        - DATABASE_URL=postgres://postgres:@localhost:5432/rblog
      tags: env
      # END - Environment


      # Custom Bashrc
    - name: Custom alias
      blockinfile:
        state: present
        path: "/home/vagrant/.bashrc"
        insertafter: EOF
        block: |
          alias python=python3
          alias py=python3
          alias pip=pip3
          alias rs='rails s -b 0.0.0.0'
          alias rc='rails c'
          alias rr='rails routes'
          alias rdb='rails db'
      become: no
      tags: bashrc

    - name: Auto change dir to project root
      lineinfile:
        dest: "/home/vagrant/.bashrc"
        line: "cd /vagrant/"
        insertafter: EOF
      become: no
      tags: bashrc
      # END - Custom bashrc


    - name: Let them know
      debug:
        msg:
          - '===================================================='
          - '|                                                  |'
          - '|            VAGRANT PROVISION FINISHED            |'
          - '|                                                  |'
          - '===================================================='
      become: no

